export interface CrochetPattern {
  id: number;
  title: string;
  description: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  yarn: string;
  hookSize: string;
  estimatedTime: string;
  imageUrl: string;
  diagramSteps: string[];
  tags: string[];
}

export const crochetPatternsData: CrochetPattern[] = [
  {
    id: 1,
    title: "小熊吊飾",
    description: "圓滾滾的小熊頭吊飾，適合初學者。",
    difficulty: "beginner",
    yarn: "棉線",
    hookSize: "3mm",
    estimatedTime: "1 小時",
    imageUrl: "https://example.com/images/bear.jpg",
    diagramSteps: [
      "R1: 6x",
      "R2: 6v = 12",
      "R3: (1x,1v)*6 = 18",
      "R4-6: 18x",
      "R7: (1x,1a)*6 = 12",
      "R8: 6a，塞棉後收針",
    ],
    tags: ["動物", "吊飾"],
  },
  {
    id: 2,
    title: "花朵杯墊",
    description: "六瓣花造型的杯墊，簡單又美觀。",
    difficulty: "beginner",
    yarn: "棉線",
    hookSize: "3mm",
    estimatedTime: "45 分鐘",
    imageUrl: "https://example.com/images/flower_coaster.jpg",
    diagramSteps: [
      "R1: 起針圈起，12長針",
      "R2: 每針加針，共24長針",
      "R3: (1長針, 1加針)*12",
      "R4: 鉤花瓣造型",
    ],
    tags: ["杯墊", "花朵"],
  },
  {
    id: 3,
    title: "蝴蝶髮夾",
    description: "繽紛蝴蝶造型，可愛髮飾。",
    difficulty: "beginner",
    yarn: "毛線",
    hookSize: "2.5mm",
    estimatedTime: "30 分鐘",
    imageUrl: "https://example.com/images/butterfly_clip.jpg",
    diagramSteps: [
      "R1: 起10鎖針，往返短針3行",
      "R2: 對折用線繞中間",
      "R3: 鉤翅膀加裝飾珠",
    ],
    tags: ["髮飾", "蝴蝶"],
  },
  {
    id: 4,
    title: "貓咪娃娃",
    description: "可愛坐姿貓娃娃，適合中階者。",
    difficulty: "intermediate",
    yarn: "混色線",
    hookSize: "4mm",
    estimatedTime: "2.5 小時",
    imageUrl: "https://example.com/images/cat_doll.jpg",
    diagramSteps: [
      "R1: 6x",
      "R2: 6v",
      "R3: (1x,1v)*6",
      "R4-6: 18x",
      "R7: (1x,1a)*6",
      "R8: 6a",
      "耳朵與四肢分別鉤製",
    ],
    tags: ["娃娃", "動物"],
  },
  {
    id: 5,
    title: "方塊吊飾",
    description: "立體方塊裝飾，可作鑰匙圈。",
    difficulty: "intermediate",
    yarn: "棉線",
    hookSize: "3mm",
    estimatedTime: "1 小時",
    imageUrl: "https://example.com/images/block.jpg",
    diagramSteps: [
      "R1: 6面各起12鎖針，短針6行",
      "R2: 縫合6面成立體方塊",
      "R3: 塞棉收針",
    ],
    tags: ["立體", "方塊", "吊飾"],
  },
  {
    id: 6,
    title: "玫瑰花杯墊",
    description: "立體玫瑰花造型，增添浪漫氛圍。",
    difficulty: "intermediate",
    yarn: "細棉線",
    hookSize: "2.5mm",
    estimatedTime: "1.5 小時",
    imageUrl: "https://example.com/images/rose_coaster.jpg",
    diagramSteps: [
      "R1: 起10鎖針，繞圈鉤短針",
      "R2: 鉤5片花瓣",
      "R3: 外圈繼續鉤大花瓣",
      "R4: 加杯墊底部圓片",
    ],
    tags: ["杯墊", "花朵"],
  },
  {
    id: 7,
    title: "花邊髮圈",
    description: "優雅花邊造型，氣質髮飾。",
    difficulty: "beginner",
    yarn: "彈性線",
    hookSize: "3mm",
    estimatedTime: "30 分鐘",
    imageUrl: "https://example.com/images/frill_hairtie.jpg",
    diagramSteps: [
      "R1: 包住髮圈鉤短針一圈",
      "R2: 每針2長針形成花邊",
      "R3: 鉤一圈緊針收尾",
    ],
    tags: ["髮飾", "花邊"],
  },
  {
    id: 8,
    title: "熊熊娃娃",
    description: "療癒小熊，送禮首選。",
    difficulty: "intermediate",
    yarn: "絨毛線",
    hookSize: "4mm",
    estimatedTime: "3 小時",
    imageUrl: "https://example.com/images/teddy.jpg",
    diagramSteps: [
      "R1: 6x",
      "R2: 6v",
      "R3: (1x,1v)*6",
      "R4-8: 18x",
      "R9: (1x,1a)*6",
      "R10: 6a",
      "耳朵、手腳分別製作",
    ],
    tags: ["娃娃", "動物"],
  },
  {
    id: 9,
    title: "格子杯墊",
    description: "經典格子圖案，百搭家飾。",
    difficulty: "beginner",
    yarn: "棉線",
    hookSize: "3mm",
    estimatedTime: "1 小時",
    imageUrl: "https://example.com/images/checker_coaster.jpg",
    diagramSteps: [
      "R1: 起鏈20，短針10行",
      "R2: 換色鉤方格",
      "R3: 四邊加緊針收尾",
    ],
    tags: ["杯墊", "格紋"],
  },
  {
    id: 10,
    title: "雙色蝴蝶髮夾",
    description: "雙色層疊蝴蝶結，增添立體感。",
    difficulty: "beginner",
    yarn: "細棉線",
    hookSize: "3mm",
    estimatedTime: "40 分鐘",
    imageUrl: "https://example.com/images/double_bow.jpg",
    diagramSteps: [
      "R1: 起15鎖針，往返短針3行（主色）",
      "R2: 重複一次副色版本",
      "R3: 疊加縫合用線綁中間",
    ],
    tags: ["髮飾", "蝴蝶結"],
  },

  {
    id: 11,
    title: "迷你背包吊飾",
    description: "小巧可愛的背包造型，可掛在鑰匙圈或包包上。",
    difficulty: "beginner",
    yarn: "棉線",
    hookSize: "3mm",
    estimatedTime: "1 小時",
    imageUrl: "https://example.com/images/mini_backpack.jpg",
    diagramSteps: [
      "R1: 起10鎖針，往返短針1行",
      "R2-5: 每行短針，形成長方形底部",
      "R6-10: 鉤立體側邊，接合形成袋身",
      "R11: 鉤袋蓋並加扣子",
    ],
    tags: ["吊飾", "背包", "配件"],
  },
  {
    id: 12,
    title: "兔耳髮圈",
    description: "兔耳造型綁髮圈，簡單又可愛。",
    difficulty: "beginner",
    yarn: "細棉線",
    hookSize: "2.5mm",
    estimatedTime: "30 分鐘",
    imageUrl: "https://example.com/images/bunny_hairtie.jpg",
    diagramSteps: [
      "R1: 包住髮圈鉤短針一圈",
      "R2: 起20鎖針，往返短針3行成兔耳",
      "R3: 另一耳朵同樣方式",
      "R4: 將兩耳固定於髮圈",
    ],
    tags: ["髮飾", "兔耳"],
  },
  {
    id: 13,
    title: "迷你相框",
    description: "小巧相框，完美展示珍貴照片。",
    difficulty: "intermediate",
    yarn: "棉線",
    hookSize: "3mm",
    estimatedTime: "2 小時",
    imageUrl: "https://example.com/images/mini_frame.jpg",
    diagramSteps: [
      "R1: 起30鎖針，短針回針至20針",
      "R2: 四邊短針，形成正方形",
      "R3: 鉤邊框並縫合，最後裝上小相框",
    ],
    tags: ["相框", "家飾"],
  },
  {
    id: 14,
    title: "迷你披肩",
    description: "小巧迷人的披肩，適合嬰兒或小孩。",
    difficulty: "intermediate",
    yarn: "細毛線",
    hookSize: "4mm",
    estimatedTime: "3 小時",
    imageUrl: "https://example.com/images/mini_shawl.jpg",
    diagramSteps: [
      "R1: 起50鎖針，織基底短針",
      "R2: 換花樣進行編織，行進至三角形",
      "R3: 完成邊緣並加入流蘇裝飾",
    ],
    tags: ["披肩", "嬰兒"],
  },
  {
    id: 15,
    title: "玫瑰花胸針",
    description: "迷人的玫瑰花胸針，增添女性魅力。",
    difficulty: "intermediate",
    yarn: "棉線",
    hookSize: "3mm",
    estimatedTime: "1.5 小時",
    imageUrl: "https://example.com/images/rose_brooch.jpg",
    diagramSteps: [
      "R1: 起10鎖針，長針圓形成花心",
      "R2: 每片花瓣加針，圍繞中心花心",
      "R3: 使用緊針固定並加上胸針針",
    ],
    tags: ["胸針", "花朵"],
  },
  {
    id: 16,
    title: "貓耳毛帽",
    description: "可愛貓耳毛線帽，保暖又有趣。",
    difficulty: "intermediate",
    yarn: "絨毛線",
    hookSize: "5mm",
    estimatedTime: "4 小時",
    imageUrl: "https://example.com/images/cat_ear_hat.jpg",
    diagramSteps: [
      "R1: 起40鎖針，圓形編織",
      "R2-5: 順行增加長針，至所需大小",
      "R6: 貓耳帽身後置兩耳部，最後縫合",
    ],
    tags: ["毛帽", "貓耳"],
  },
  {
    id: 17,
    title: "小熊手套",
    description: "可愛小熊圖案手套，適合寒冷天氣。",
    difficulty: "advanced",
    yarn: "棉線",
    hookSize: "3mm",
    estimatedTime: "5 小時",
    imageUrl: "https://example.com/images/bear_gloves.jpg",
    diagramSteps: [
      "R1: 起16鎖針，織基底短針",
      "R2: 指尖部分使用貝殼針編織",
      "R3: 手背加入小熊耳朵及眼睛裝飾",
    ],
    tags: ["手套", "小熊"],
  },
  {
    id: 18,
    title: "彩色絲巾",
    description: "五彩斑斕的長絲巾，輕巧又多功能。",
    difficulty: "beginner",
    yarn: "絲線",
    hookSize: "2mm",
    estimatedTime: "2 小時",
    imageUrl: "https://example.com/images/colorful_scarf.jpg",
    diagramSteps: [
      "R1: 起100鎖針，短針織法",
      "R2: 換色並繼續織至所需長度",
      "R3: 編織邊緣收針",
    ],
    tags: ["絲巾", "彩色"],
  },
  {
    id: 19,
    title: "圓形餐墊",
    description: "簡單大方的圓形餐墊，輕鬆搭配各式餐具。",
    difficulty: "beginner",
    yarn: "棉線",
    hookSize: "3mm",
    estimatedTime: "1 小時",
    imageUrl: "https://example.com/images/round_place_mat.jpg",
    diagramSteps: [
      "R1: 起12鎖針，圓形編織",
      "R2: 繼續每針加長針，形成圓形底面",
      "R3: 收緊邊緣，完成餐墊",
    ],
    tags: ["餐墊", "圓形"],
  },
  {
    id: 20,
    title: "蝴蝶披肩",
    description: "蝴蝶形狀的美麗披肩，優雅浪漫。",
    difficulty: "advanced",
    yarn: "毛線",
    hookSize: "4mm",
    estimatedTime: "6 小時",
    imageUrl: "https://example.com/images/butterfly_shawl.jpg",
    diagramSteps: [
      "R1: 起30鎖針，形成三角形基底",
      "R2: 換成蝴蝶形狀進行編織",
      "R3: 完成邊緣裝飾並固定",
    ],
    tags: ["披肩", "蝴蝶"],
  },
  {
    id: 21,
    title: "小鹿娃娃",
    description: "可愛的小鹿娃娃，適合作為玩具。",
    difficulty: "intermediate",
    yarn: "絨毛線",
    hookSize: "4mm",
    estimatedTime: "3 小時",
    imageUrl: "https://example.com/images/deer_doll.jpg",
    diagramSteps: [
      "R1: 起6針，圓形編織",
      "R2: 擴展編織，直到有18針",
      "R3: 加裝鹿角和眼睛，縫合完成",
    ],
    tags: ["娃娃", "小鹿"],
  },
  {
    id: 22,
    title: "長袖毛衣",
    description: "溫暖的長袖毛衣，適合秋冬穿著。",
    difficulty: "advanced",
    yarn: "羊毛線",
    hookSize: "5mm",
    estimatedTime: "10 小時",
    imageUrl: "https://example.com/images/sweater.jpg",
    diagramSteps: [
      "R1: 起40鎖針，織長針基底",
      "R2-10: 持續增加長針，形成袖子和衣身",
      "R11: 加入肩部和袖口修整",
    ],
    tags: ["毛衣", "長袖"],
  },
  {
    id: 23,
    title: "小巧圓包",
    description: "圓形迷你包包，輕巧又實用。",
    difficulty: "intermediate",
    yarn: "棉線",
    hookSize: "3mm",
    estimatedTime: "2 小時",
    imageUrl: "https://example.com/images/mini_bag.jpg",
    diagramSteps: [
      "R1: 起16鎖針，圓形基底",
      "R2: 每針加針，圓形增大至所需大小",
      "R3: 鉤包包邊緣，繫上扣環",
    ],
    tags: ["包包", "圓形"],
  },
  {
    id: 24,
    title: "大星星掛飾",
    description: "巨型星星掛飾，為房間增添亮點。",
    difficulty: "beginner",
    yarn: "亮片線",
    hookSize: "6mm",
    estimatedTime: "1.5 小時",
    imageUrl: "https://example.com/images/star_hanger.jpg",
    diagramSteps: [
      "R1: 起10鎖針，編織星星五角形基底",
      "R2: 每角加入加針，繼續編織",
      "R3: 完成星星並加上吊環",
    ],
    tags: ["掛飾", "星星"],
  },
  {
    id: 25,
    title: "手工花環",
    description: "美麗的花環，為家中增添生氣。",
    difficulty: "intermediate",
    yarn: "棉線",
    hookSize: "3mm",
    estimatedTime: "2 小時",
    imageUrl: "https://example.com/images/flower_wreath.jpg",
    diagramSteps: [
      "R1: 起20鎖針，編織圓形基底",
      "R2: 鉤花瓣，加入綠色葉子",
      "R3: 完成花環並加上綁繩",
    ],
    tags: ["花環", "家飾"],
  },
  {
    id: 26,
    title: "四葉草吊飾",
    description: "四葉草形狀的幸運吊飾。",
    difficulty: "beginner",
    yarn: "棉線",
    hookSize: "3mm",
    estimatedTime: "1 小時",
    imageUrl: "https://example.com/images/four_leaf_clover.jpg",
    diagramSteps: [
      "R1: 起6鎖針，編織圓形",
      "R2: 加花瓣形狀的針",
      "R3: 完成四葉草並加上吊環",
    ],
    tags: ["吊飾", "四葉草"],
  },
  {
    id: 27,
    title: "小丑帽",
    description: "有趣的小丑帽，歡樂又獨特。",
    difficulty: "advanced",
    yarn: "毛線",
    hookSize: "4mm",
    estimatedTime: "5 小時",
    imageUrl: "https://example.com/images/clown_hat.jpg",
    diagramSteps: [
      "R1: 起30鎖針，編織圓形帽子",
      "R2: 加入小丑帽頂的彩條",
      "R3: 完成帽子並加裝飾",
    ],
    tags: ["帽子", "小丑"],
  },
  {
    id: 28,
    title: "花瓣圍巾",
    description: "圍巾加入花瓣設計，顯得更加別致。",
    difficulty: "intermediate",
    yarn: "棉線",
    hookSize: "3mm",
    estimatedTime: "3 小時",
    imageUrl: "https://example.com/images/petal_scarf.jpg",
    diagramSteps: [
      "R1: 起60鎖針，編織長針基底",
      "R2: 每行編織花瓣形狀",
      "R3: 完成圍巾並固定花瓣",
    ],
    tags: ["圍巾", "花瓣"],
  },
  {
    id: 29,
    title: "大蝴蝶結髮夾",
    description: "巨大的蝴蝶結髮夾，增添甜美感。",
    difficulty: "beginner",
    yarn: "絲線",
    hookSize: "2.5mm",
    estimatedTime: "30 分鐘",
    imageUrl: "https://example.com/images/large_bow_clip.jpg",
    diagramSteps: [
      "R1: 起15鎖針，編織花瓣形狀",
      "R2: 組合大蝴蝶結，縫合於髮夾上",
    ],
    tags: ["髮夾", "蝴蝶結"],
  },
  {
    id: 30,
    title: "草莓包包",
    description: "草莓造型的小包包，讓你充滿甜美氣息。",
    difficulty: "intermediate",
    yarn: "棉線",
    hookSize: "3mm",
    estimatedTime: "3 小時",
    imageUrl: "https://example.com/images/strawberry_bag.jpg",
    diagramSteps: [
      "R1: 起6鎖針，編織圓形基底",
      "R2: 加針形成草莓形狀",
      "R3: 鉤上綠葉和小柄",
    ],
    tags: ["包包", "草莓"],
  },
];
